# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieBox' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieBox
  pod 'Alamofire', '~> 5.4'
  pod 'SCLAlertView'
  pod 'SDWebImage', '~> 5.0'

  target 'MovieBoxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieBoxUITests' do
    # Pods for testing
  end

end
