//
//  DashboardViewController.swift
//  MovieBox
//
//  Created by Onder on 25.06.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SnapKit

protocol DashboardViewDisplayLogic: class {
    func displayPopularMovies(movieListViewModel: MovieListViewModel)
}

class DashboardViewController: BaseViewControlller, DashboardViewDisplayLogic {

    // MARK: Properties
    
    var interactor: DashboardViewBusinessLogic?
    var router: (NSObjectProtocol & DashboardViewRoutingLogic & DashboardViewDataPassing)?
    
    var movieListViewModel: MovieListViewModel?
    
    fileprivate let collectionView:UICollectionView = {
        let layout = UICollectionViewFlowLayout()
        layout.scrollDirection = .vertical
        let cv = UICollectionView(frame: .zero, collectionViewLayout: layout)
        cv.translatesAutoresizingMaskIntoConstraints = false
        cv.register(MovieCell.self, forCellWithReuseIdentifier: "cell")
        cv.register(SectionHeader.self, forSupplementaryViewOfKind: UICollectionView.elementKindSectionHeader, withReuseIdentifier: "header")
        return cv
    }()
    
    // MARK: Constants
    
    enum Constants {
        static let sectionNumber: Int = 2
    }
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
  
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        title = "Movies & People"
        
        setupCollectionView()
        
        interactor?.getPopularMovies(forpage: 1)
    }
  
    // MARK: Setup
  
    private func setup() {
        let viewController = self
        let interactor = DashboardViewInteractor()
        let presenter = DashboardViewPresenter()
        let router = DashboardViewRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
        
       // initCollectionView()
    }

//    private func initCollectionView() {
//        let layout = UICollectionViewFlowLayout()
//        layout.scrollDirection = .horizontal
//        collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
//        collectionView.translatesAutoresizingMaskIntoConstraints = false
//        collectionView.register(CustomCell.self, forCellWithReuseIdentifier: "cell")
//    }
    
    private func setupCollectionView() {
        view.addSubview(collectionView)
        collectionView.backgroundColor = .white
        collectionView.delegate = self
        collectionView.dataSource = self
        
        collectionView.snp.makeConstraints({ (make) in
            make.trailing.equalToSuperview()
            make.bottom.equalToSuperview()
            make.top.equalToSuperview()
            make.leading.equalTo(view.snp.trailing)
            make.width.equalTo(view.snp.width)
        })
    }
    
    // MARK: DashboardViewDisplayLogic
    
    func displayPopularMovies(movieListViewModel: MovieListViewModel) {
        self.movieListViewModel = movieListViewModel
        collectionView.reloadData()
    }
}
