//
//  DashboardViewWorker.swift
//  MovieBox
//
//  Created by Onder on 25.06.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

protocol DashboardViewWorkerProtocol {
    func getPopularMovies(forpage page:Int, completionHandler:@escaping (() throws -> MovieListViewModel) -> Void)
}

final class DashboardViewWorker {
    
    func getPopularMovies(forpage page:Int,
                          completionHandler:@escaping (MovieListViewModel?, Error?) -> Void) {
        
        let params: Parameters = [
            "api_key": Constants.apiKey,
            "page" : String(page)
            ]
        
        AF.request(TransactionURL.getPopularMovies.urlString,
                   method: .get,
                   parameters: params,
                   encoding: URLEncoding.queryString)
            
            .responseDecodable(of: MovieListViewModel.self) { response in
                
                switch response.result {
                    case .success(let movieListViewModel):
                        completionHandler(movieListViewModel, nil)
                        
                    case .failure(let error):
                        completionHandler(nil, error)
                }
        }
    }
}
