//
//  DashboardViewPresenter.swift
//  MovieBox
//
//  Created by Onder on 25.06.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DashboardViewPresentationLogic {
    func presentPopularMovies(movieListViewModel: MovieListViewModel)
    func presentSearchedMovies(movieListViewModel: MovieListViewModel)
    func presentSearchedPeople(peopleListViewModel: PeopleListViewModel)
    func presentBothSearchedPeopleAndMovie(movieListViewModel: MovieListViewModel,
                                           peopleListViewModel: PeopleListViewModel)
}

class DashboardViewPresenter: DashboardViewPresentationLogic
{
    weak var viewController: DashboardViewDisplayLogic?
  
    func presentPopularMovies(movieListViewModel: MovieListViewModel) {
        viewController?.displayPopularMovies(movieListViewModel: movieListViewModel)
    }
    
    func presentSearchedMovies(movieListViewModel: MovieListViewModel) {
        viewController?.displaySearchedMovies(movieListViewModel: movieListViewModel)
    }
    
    func presentSearchedPeople(peopleListViewModel: PeopleListViewModel) {
        viewController?.displaySearchedPeople(peopleListViewModel: peopleListViewModel)
    }
    
    func presentBothSearchedPeopleAndMovie(movieListViewModel: MovieListViewModel,
                                           peopleListViewModel: PeopleListViewModel) {
        viewController?.displayBothSearchedPeopleAndMovie(movieListViewModel: movieListViewModel,
                                                          peopleListViewModel: peopleListViewModel)
    }
}
