//
//  DashboardViewModels.swift
//  MovieBox
//
//  Created by Onder on 25.06.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DashboardSections: Int {
    case Movie
    case Person
}


struct Person: Decodable {
    let id: Int
    let name: String?
    let image: String?
    
    enum CodingKeys: String, CodingKey {
        case id
        case name
        case image = "profile_path"
    }
}

struct PeopleListViewModel: Decodable {
    var items: [Person]
    let totalPages: Int
    let totalResults: Int
    let page: Int
    
    enum CodingKeys: String, CodingKey {
        case items = "results"
        case totalPages = "total_pages"
        case totalResults = "total_results"
        case page = "page"
    }
}

struct Movie: Decodable {
    let id: Int
    let title: String?
    let descripton: String?
    let posterPath: String?
    let backdropPath: String?
    
    enum CodingKeys: String, CodingKey {
        case id
        case title = "original_title"
        case descripton = "overview"
        case posterPath = "poster_path"
        case backdropPath = "backdrop_path"
    }
}

struct MovieListViewModel: Decodable {
    var items: [Movie]
    let totalPages: Int
    let totalResults: Int
    let page: Int
    
    enum CodingKeys: String, CodingKey {
        case items = "results"
        case totalPages = "total_pages"
        case totalResults = "total_results"
        case page = "page"
    }
}
