//
//  DashboardViewRouter.swift
//  MovieBox
//
//  Created by Onder on 25.06.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DashboardViewRoutingLogic {
  
}

protocol DashboardViewDataPassing {
    var dataStore: DashboardViewDataStore? { get }
}

class DashboardViewRouter: NSObject, DashboardViewRoutingLogic, DashboardViewDataPassing {
    weak var viewController: DashboardViewController?
    var dataStore: DashboardViewDataStore?
  
    // MARK: Routing
  

    // MARK: Navigation
  
  
    // MARK: Passing data
  
}
