//
//  DashboardViewPresenter.swift
//  MovieBox
//
//  Created by Onder on 25.06.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DashboardViewPresentationLogic
{
  func presentSomething(response: DashboardView.Something.Response)
}

class DashboardViewPresenter: DashboardViewPresentationLogic
{
  weak var viewController: DashboardViewDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: DashboardView.Something.Response)
  {
    let viewModel = DashboardView.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
